on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: 'zeckcg7jlal6q-fhir-dashboard'
  AZURE_WEBAPP_PACKAGE_PATH: './dashboard'
  NODE_VERSION: '14.x' 

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest    
    environment: production
    steps:    
    - name: Az Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: actions/checkout@v2    
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
