on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_PACKAGE_PATH: './dashboard'
  AZURE_SUBSCRIPTION_ID: '1c642d88-5042-4d19-9d49-49be6612a40f'
  AZURE_RESOURCE_GROUP: 'rg-chestist'
  AZURE_REGISTRY_NAME: 'chestistzec'
  DOTNET_VERSION: '3.1'

jobs:
  docker-build:
    name: Build and push chestist-smart-app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: chestist-smart-app
    steps:
    - 
      name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    -
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Yarn install and build
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: yarn install
    - run: yarn build

    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to Azure ACR
      run: |
        az acr login --name ${{ env.AZURE_REGISTRY_NAME }}        
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./chestist-smart-app
        push: true
        tags: '${{ env.AZURE_REGISTRY_NAME }}.azurecr.io/chestist-smart-app:${{ github.sha }}'   

  provision:
    name: Provision Azure Webapp Resources
    runs-on: ubuntu-latest
    needs: docker-build
    outputs: 
      azure-webapp-name: ${{ steps.deploy-bicep.outputs.fhirDashboardAppName }}
      imageapi-func-name: ${{ steps.deploy-bicep.outputs.imageApiFuncAppName }}
    steps:                
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Checkout
    - name: Checkout
      uses: actions/checkout@v1
        
    # Deployment of template    
    - name: Deploy BICEP Template
      id: deploy-bicep
      uses: azure/arm-deploy@v1      
      with:
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        template: ./deploy/smart-on-fhir-apps.bicep  # Set this to the location of your template file
        parameters: 'aadClientSecret=${{ secrets.FHIR_CLIENT_SECRET }} chestistImageName=chestist-smart-app:${{ github.sha }}' # Set this to the location of your parameters file
        failOnStdErr: false


  build-and-deploy-dashboard:
    name: Build and Deploy Dashboard
    runs-on: ubuntu-latest   
    needs: provision 
    environment: production
    steps:    
    - name: Az Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: actions/checkout@v2    
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ needs.provision.outputs.azure-webapp-name }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  build-and-deploy-function:
    name: Build and Deploy Image API
    runs-on: ubuntu-latest
    needs: provision
    environment: production    
    steps:
    - name: Az Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './Chestist.Imaging.Api'
        dotnet build --configuration Release --output ./output
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ needs.provision.outputs.imageapi-func-name }}
        package: './Chestist.Imaging.Api/output'
