on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_PACKAGE_PATH: './dashboard'
  AZURE_SUBSCRIPTION_ID: '1c642d88-5042-4d19-9d49-49be6612a40f'
  AZURE_RESOURCE_GROUP: 'rg-chestist'

jobs:
  provision:
    name: Provision Azure Resources
    runs-on: ubuntu-latest
    outputs: 
      azure-webapp-name: ${{ steps.deploy-bicep.outputs.fhirDashboardAppName }}
    steps:                
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Checkout
    - name: Checkout
      uses: actions/checkout@v1
        
    # Deployment of template    
    - name: Deploy BICEP Template
      id: deploy-bicep
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        template: ./deploy/modules/dashboard.bicep  # Set this to the location of your template file
        parameters: 'aadClientSecret=${{ secrets.FHIR_CLIENT_SECRET }}' # Set this to the location of your parameters file


  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest   
    needs: provision 
    environment: production
    steps:    
    - name: Az Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: actions/checkout@v2    
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ needs.provision.outputs.azure-webapp-name }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
